#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
VASP 文件读写工具 (ESP 表面可视化用)。

* read_structure()   : 解析 POSCAR / CONTCAR / LOCPOT / CHGCAR 头部的结构信息
* read_vasp_volume() : 解析 LOCPOT / CHGCAR / POT, 取出第一块网格数据 (电势/电荷密度)
* downsample()       : 网格降采样 (满足浏览器内存与实时等值面计算)
* cube_header()      : 生成 3Dmol.js VolumeData 所需的极简 cube 几何头

约定:
    * 长度单位: Å (埃)
    * 网格数据索引顺序: x 最快 -> z 最慢, 与 VASP / cube 一致
"""

from __future__ import annotations

import base64
import math
from dataclasses import dataclass, field
from typing import Callable, List, Optional, Sequence, Tuple

import numpy as np

# 玻尔半径 (Å) —— cube 文件使用玻尔单位
BOHR = 0.529177210903


# ==========================================================================
# 结构
# ==========================================================================
@dataclass
class Structure:
    cell: np.ndarray            # 3x3, 行 = a/b/c 矢量, 单位 Å
    symbols: List[str]          # 每个原子的元素符号
    cart: np.ndarray            # Nx3 笛卡尔坐标, 单位 Å

    @property
    def n_atoms(self) -> int:
        return len(self.symbols)

    def xyz(self) -> str:
        lines = [str(self.n_atoms), "generated by ESP Viewer"]
        for s, (x, y, z) in zip(self.symbols, self.cart):
            lines.append(f"{s} {x:.6f} {y:.6f} {z:.6f}")
        return "\n".join(lines) + "\n"

    def params(self) -> Tuple[float, float, float, float, float, float]:
        """返回 (a, b, c, alpha, beta, gamma)。"""
        a, b, c = (float(np.linalg.norm(v)) for v in self.cell)
        cos_a = float(np.dot(self.cell[1], self.cell[2]) / (b * c))
        cos_b = float(np.dot(self.cell[0], self.cell[2]) / (a * c))
        cos_g = float(np.dot(self.cell[0], self.cell[1]) / (a * b))
        ang = lambda x: math.degrees(math.acos(max(-1.0, min(1.0, x))))  # noqa: E731
        return a, b, c, ang(cos_a), ang(cos_b), ang(cos_g)

    def cell_edges(self) -> List[List[float]]:
        """12 条晶胞棱 (每条为 [x1,y1,z1,x2,y2,z2])。"""
        a, b, c = self.cell
        o = np.zeros(3)
        corners = [o, a, b, c, a + b, a + c, b + c, a + b + c]
        pairs = [(0, 1), (0, 2), (0, 3), (1, 4), (1, 5),
                 (2, 4), (2, 6), (3, 5), (3, 6), (4, 7), (5, 7), (6, 7)]
        return [[*corners[i].tolist(), *corners[j].tolist()] for i, j in pairs]


# ==========================================================================
# 解析
# ==========================================================================
def _is_int(tok: str) -> bool:
    try:
        int(tok)
        return True
    except ValueError:
        return False


def read_structure(f) -> Structure:
    """从已打开的文本文件句柄读取 VASP 结构块 (VASP5; 兼容 VASP4)。"""
    f.readline()                                   # 第 1 行: 标题
    scale_line = f.readline()
    scale = float(scale_line.split()[0]) if scale_line.split() else 1.0
    cell = np.array(
        [[float(x) for x in f.readline().split()[:3]] for _ in range(3)],
        dtype=float,
    ) * scale

    tokens = f.readline().split()                  # 元素符号 或 计数
    second = f.readline().split()

    if second and all(_is_int(t) for t in second):
        names = tokens
        counts = [int(t) for t in second]
        mode_line = f.readline()
    else:                                          # VASP4: 无元素名
        names = ["X"] * len(tokens)
        counts = [int(t) for t in tokens]
        mode_line = " ".join(second)

    mode = mode_line.strip()
    if mode.lower().startswith("s"):               # Selective dynamics
        mode = f.readline().strip()
    direct = mode[:1].lower() == "d"

    symbols: List[str] = []
    for name, cnt in zip(names, counts):
        symbols.extend([name] * cnt)

    coords = []
    for _ in range(len(symbols)):
        parts = f.readline().split()
        coords.append([float(parts[0]), float(parts[1]), float(parts[2])])
    coords = np.asarray(coords, dtype=float)

    cart = coords @ cell if direct else coords * scale
    return Structure(cell=cell, symbols=symbols, cart=cart)


def read_vasp_volume(
    path: str,
    progress: Optional[Callable[[int, int], None]] = None,
) -> Tuple[Structure, Tuple[int, int, int], np.ndarray]:
    """
    读取 VASP LOCPOT / CHGCAR / POT 的第一块网格数据。

    返回 (结构, (nx, ny, nz), data[nx,ny,nz])。
    data 按 x 最快排列, 与 VASP 写出顺序一致。
    """
    with open(path, "r", errors="replace") as f:
        struct = read_structure(f)

        line = f.readline()
        while line and not line.strip():           # 跳过空行
            line = f.readline()
        if not line:
            raise ValueError("文件在结构之后缺少网格尺寸行")

        dims = [int(x) for x in line.split()[:3]]
        if len(dims) != 3:
            raise ValueError("无法解析网格尺寸")
        nx, ny, nz = dims
        need = nx * ny * nz

        chunks: List[str] = []
        count = 0
        last_report = 0
        while count < need:
            ln = f.readline()
            if not ln:
                break
            chunks.append(ln)
            count += len(ln.split())
            if progress is not None and count - last_report >= 200000:
                last_report = count
                progress(min(count, need), need)

        text = "".join(chunks)
        data = np.fromstring(text, dtype=np.float64, sep=" ")  # noqa: NPY201
        if data.size < need:
            raise ValueError(f"网格数据不足: 需要 {need}, 实际 {data.size}")
        # 关键: VASP 以 x 最快 / z 最慢写出, 而 3Dmol 的 VolumeData(cube)
        # 与 MarchingCube 都以 x 最慢 / z 最快索引 (flat = x*ny*nz + y*nz + z)。
        # 因此必须按 Fortran 顺序 reshape, 得到 axes=(x,y,z) 的物理数组,
        # 否则 x/z 被交换, 电势/密度面方向就是错的。
        data = data[:need].reshape((nx, ny, nz), order="F")
        if progress is not None:
            progress(need, need)

    return struct, (nx, ny, nz), data


# ==========================================================================
# 降采样 / cube 几何
# ==========================================================================
def downsample(data: np.ndarray, factor: int) -> np.ndarray:
    factor = max(1, int(factor))
    return np.ascontiguousarray(data[::factor, ::factor, ::factor])


def cube_header(nx: int, ny: int, nz: int, cell: np.ndarray) -> str:
    """
    生成极简 cube 头 (不含原子、不含数据), 供 3Dmol.js 的 VolumeData
    解析出 origin / size / unit / matrix。坐标一律用玻尔。
    """
    cell_bohr = np.asarray(cell, dtype=float) / BOHR
    vx = cell_bohr[0] / nx
    vy = cell_bohr[1] / ny
    vz = cell_bohr[2] / nz
    return (
        "ESP volume\n"
        "generated by ESP Viewer\n"
        "0 0.000000 0.000000 0.000000\n"
        f"{nx} {vx[0]:.8f} {vx[1]:.8f} {vx[2]:.8f}\n"
        f"{ny} {vy[0]:.8f} {vy[1]:.8f} {vy[2]:.8f}\n"
        f"{nz} {vz[0]:.8f} {vz[1]:.8f} {vz[2]:.8f}\n"
    )


def volume_base64(data: np.ndarray) -> str:
    """把网格转成小端 float32 的 base64, 便于嵌入 HTML。"""
    arr = np.ascontiguousarray(data, dtype="<f4")
    return base64.b64encode(arr.tobytes()).decode("ascii")


def percentiles(data: np.ndarray, qs: Sequence[float]) -> List[float]:
    return [float(np.percentile(data, q)) for q in qs]


def write_vasp_volume(path, struct: "Structure", data: np.ndarray,
                      title: str = "ESP sample") -> None:
    """把网格写成 VASP 格式 (LOCPOT/CHGCAR), 供打包内置样例使用。

    data: 物理数组 axes=(x,y,z); 写出时转成 VASP 的 x 最快顺序。
    """
    nx, ny, nz = data.shape
    order, counts = [], {}
    for s in struct.symbols:
        if s not in counts:
            counts[s] = 0
            order.append(s)
        counts[s] += 1
    frac = struct.cart @ np.linalg.inv(struct.cell)
    flat = np.asarray(data).ravel(order="F")          # x 最快
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"{title}\n")
        f.write("   1.00000000000000\n")
        for v in struct.cell:
            f.write("  %20.12f %20.12f %20.12f\n" % tuple(v))
        f.write("   " + "   ".join(order) + "\n")
        f.write("   " + "   ".join(str(counts[s]) for s in order) + "\n")
        f.write("Direct\n")
        for c in frac:
            f.write("  %19.16f %19.16f %19.16f\n" % tuple(c))
        f.write("\n")
        f.write("   %d   %d   %d\n" % (nx, ny, nz))
        for i in range(0, flat.size, 5):
            f.write("".join(" %19.11E" % v for v in flat[i:i + 5]) + "\n")


# ==========================================================================
# 六标准视角 / 取景包围球 (基于实际晶胞矢量)
# ==========================================================================
# 3Dmol 的 getView() 四元数把模型旋转到相机系: 屏幕 x = R_row0 · v,
# 屏幕 y = R_row1 · v。因此把旋转矩阵三行设为 ex/ey/ez 即可。
VIEW_NAMES = ["front", "back", "top", "bottom", "right", "left"]


def _unit(v: np.ndarray) -> np.ndarray:
    v = np.asarray(v, dtype=float)
    n = float(np.linalg.norm(v))
    if n < 1e-12:
        return np.array([1.0, 0.0, 0.0])
    return v / n


def _quat_from_matrix(m: np.ndarray) -> List[float]:
    """3x3 正交旋转矩阵 -> 四元数 (x, y, z, w), 与 three.js/3Dmol 一致。"""
    m = np.asarray(m, dtype=float)
    t = float(m[0, 0] + m[1, 1] + m[2, 2])
    if t > 0.0:
        s = math.sqrt(t + 1.0) * 2.0
        w = 0.25 * s
        x = (m[2, 1] - m[1, 2]) / s
        y = (m[0, 2] - m[2, 0]) / s
        z = (m[1, 0] - m[0, 1]) / s
    elif m[0, 0] > m[1, 1] and m[0, 0] > m[2, 2]:
        s = math.sqrt(1.0 + m[0, 0] - m[1, 1] - m[2, 2]) * 2.0
        w = (m[2, 1] - m[1, 2]) / s
        x = 0.25 * s
        y = (m[0, 1] + m[1, 0]) / s
        z = (m[0, 2] + m[2, 0]) / s
    elif m[1, 1] > m[2, 2]:
        s = math.sqrt(1.0 + m[1, 1] - m[0, 0] - m[2, 2]) * 2.0
        w = (m[0, 2] - m[2, 0]) / s
        x = (m[0, 1] + m[1, 0]) / s
        y = 0.25 * s
        z = (m[1, 2] + m[2, 1]) / s
    else:
        s = math.sqrt(1.0 + m[2, 2] - m[0, 0] - m[1, 1]) * 2.0
        w = (m[1, 0] - m[0, 1]) / s
        x = (m[0, 2] + m[2, 0]) / s
        y = (m[1, 2] + m[2, 1]) / s
        z = 0.25 * s
    q = np.array([x, y, z, w], dtype=float)
    nrm = float(np.linalg.norm(q))
    if nrm < 1e-12:
        return [0.0, 0.0, 0.0, 1.0]
    q /= nrm
    if q[3] < 0:
        q = -q
    return [float(v) for v in q]


def view_quaternion(cell: np.ndarray, name: str) -> List[float]:
    """晶胞矢量计算出标准视角四元数。

    正/后视: a→屏幕 x, c→屏幕 y; 俯/仰视: a→x, b→y; 左/右视: b→x, c→y。
    """
    cell = np.asarray(cell, dtype=float).reshape(3, 3)
    a, b, c = cell[0], cell[1], cell[2]
    if name in ("front", "back"):
        ex, ey = _unit(a), c
    elif name in ("top", "bottom"):
        ex, ey = _unit(a), b
    else:                                   # right / left
        ex, ey = _unit(b), c
    if name in ("back", "bottom", "left"):
        ex = -ex
    ey = np.asarray(ey, dtype=float) - float(np.dot(ey, ex)) * ex
    ey = _unit(ey)
    ez = _unit(np.cross(ex, ey))
    return _quat_from_matrix(np.array([ex, ey, ez]))


def view_quaternions(cell: np.ndarray) -> dict:
    out = {}
    for name in VIEW_NAMES:
        try:
            out[name] = view_quaternion(cell, name)
        except Exception:  # noqa: BLE001
            out[name] = [0.0, 0.0, 0.0, 1.0]
    return out


def fit_sphere(struct: "Structure", include_cell: bool = None) -> List[float]:
    """取景包围球 [cx, cy, cz, radius]。

    include_cell=None (默认自动): 若晶胞盒远大于原子范围 (分子+大真空盒),
    则只按原子取景; 否则连同晶胞盒一起装下 (表面/体相结构)。
    """
    atoms = np.asarray(struct.cart, dtype=float)
    ca = (atoms.min(0) + atoms.max(0)) / 2.0
    r_atom = max(float(np.linalg.norm(atoms - ca, axis=1).max()), 1.0)

    a, b, c = struct.cell
    o = np.zeros(3)
    corners = np.array([o, a, b, c, a + b, a + c, b + c, a + b + c])
    cc = (corners.min(0) + corners.max(0)) / 2.0
    r_cell = float(np.linalg.norm(corners - cc, axis=1).max())

    if include_cell is None:
        include_cell = r_cell < 2.0 * r_atom

    pts = [atoms]
    if include_cell:
        pts.append(corners)
    allp = np.vstack([p for p in pts if len(p)])
    lo, hi = allp.min(0), allp.max(0)
    center = (lo + hi) / 2.0
    radius = float(np.linalg.norm(allp - center, axis=1).max())
    return [float(center[0]), float(center[1]), float(center[2]),
            max(radius, 1.0), 1.0 if include_cell else 0.0]
